AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  graphql-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
Parameters:
  DATABASE:
    Default: database
    Description: Database name
    Type: String
  ENDPOINT:
    Default: endpoint
    Description: Database endpoint
    Type: String
  USERNAME:
    Default: username
    Description: Database username
    Type: String
  PASSWORD:
    Default: password
    Description: Database password
    Type: String

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  GraphQLFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: dist/src/index.server
      CodeUri: functions/graphql-server
      Layers:
        - !Ref GlobalDependenciesLayer
      Runtime: nodejs14.x
      Events:
        GraphQL:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api
            Method: get
        Api1:
          Type: Api
          Properties:
            Path: /api
            Method: POST
      Environment:
        Variables:
          DATABASE: !Ref DATABASE
          ENDPOINT: !Ref ENDPOINT
          USERNAME: !Ref USERNAME
          PASSWORD: !Ref PASSWORD
  GlobalDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GlobalDependenciesLayer
      ContentUri: layers/global-dependencies
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs14.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for GraphQL function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
